openapi: 3.1.0
components:
  schemas:
    BloodOrange:
        type: object
        properties:
            seeds:
              type: integer
            color:
              $ref: "../../colors/schemas.yaml#/OrangeRed"